# Generated by Django 3.2.19 on 2023-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_id',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='story_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
