# Generated by Django 3.2.19 on 2023-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20230905_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='genated_content',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='unique_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
