# Generated by Django 3.2.19 on 2023-09-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20230907_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='unique_id',
            field=models.CharField(max_length=1000),
        ),
    ]
