# Generated by Django 3.2.19 on 2023-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='ebook_format',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
